services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 5s
      timeout: 5s
      retries: 5

  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     DATABASE_URL: postgres://root:root@db/postgres
  #     BACKEND_URL: 0.0.0.0
  #     BACKEND_PORT: 3000
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     db:
  #       condition: service_healthy

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - VITE_API_URL=http://localhost:3000
  #   depends_on:
  #     - backend

volumes:
  postgres-data:
